### ISSUE TITLE
When using the Django TestCases, _pre_setup is run after setUp

### ISSUE THREAD

**Issue by gcbirzan** [HypothesisWorks/hypothesis-python#343] opened 2016-07-05 14:23 UTC
This results in code that works with the default django test cases not working with hypothesis, if one tries to use, for example, self.client in setUp.

I've written a [test](https://gist.github.com/gcbirzan/cbf7af5097755043317579813b1e248e) for this.

**Comment by DRMacIver** [comment] 2016-07-13 14:33
I've been looking into this and I don't think it's fixable without some serious rethinking of how setUp and tearDown are handled in Hypothesis in general I'm afraid. I'll continue thinking about this, but for now I'm afraid my recommendation is to not use setUp.

**Comment by DRMacIver** [comment] 2016-07-13 14:33
(This falls into the general pattern of test fixtures being run once for the whole test rather than once per example)

**Comment by Zac-HD** [comment] 2017-05-31 04:08
Duplicate of #59

**Closed** 2018-02-19 12:41 UTC
Labels: duplicate
