### ISSUE TITLE
No tests are run

### ISSUE THREAD

**Issue by yurivict** [HypothesisWorks/hypothesis-python#950] opened 2017-10-20 06:08 UTC
Tests aren't run for the FreeBSD port. Command is ```python -m pytest```. Version 3.33.0.

```
==================================================================================== test session starts =====================================================================================
platform freebsd11 -- Python 2.7.13, pytest-3.2.1, py-1.4.34, pluggy-0.4.0
rootdir: /usr/ports/devel/py-hypothesis/work/hypothesis-3.33.0, inifile:
plugins: xdist-1.13.1, hypothesis-1.18.1
collected 0 items                                                                                                                                                                             

================================================================================ no tests ran in 0.03 seconds ================================================================================
*** Error code 5

Stop.
make: stopped in /usr/ports/devel/py-hypothesis

shell returned 1
```

**Comment by kxepal** [comment] 2017-10-20 07:10
Hi!
It seems you have custom port. Upstream one doesn't run tests via pytest. Could you share it?

Also `plugins: xdist-1.13.1, hypothesis-1.18.1` while you test version 3.33.0 - that's looks suspicious.

**Comment by yurivict** [comment] 2017-10-20 07:32
My:
```
do-test:
        @(cd ${WRKSRC} && ${PYTHON_CMD} -m pytest)
```

Upstream:
```
do-test:
	@(cd ${WRKSRC} && ${PYTHON_CMD} ${PYDISTUTILS_SETUP} test)
```

Both don't run tests.

**Comment by Zac-HD** [comment] 2017-10-21 12:02
This still sounds like a bug in the downstream package to me, not in Hypothesis itself.

Can you run the tests from a clone of this git repo?

**Comment by yurivict** [comment] 2017-10-22 05:17
```python2 setup.py test``` doesn't run tests in the repository clone.

**Comment by Zac-HD** [comment] 2017-10-22 11:28
Try `make check-py36`

**Comment by yurivict** [comment] 2017-10-22 16:20
> make check-py36

It has no makefile.

**Comment by Zac-HD** [comment] 2017-10-23 00:33
It sounds like you're still using a downstream package, which is not this repo - we certainly do have a makefile - and they're deleting parts of the package.  If you have similar problems when installing Hypothesis from the original source (*this* repo), or bugs in the most recent `pip install`ed version, please open a new issue; I'm closing this one as downstream packages are not our problem.

**Closed by Zac-HD** 2017-10-23 00:33 UTC

**Comment by yurivict** [comment] 2017-10-23 01:27
I use the package downloaded from CHEESESHOP.

**Comment by Zac-HD** [comment] 2017-10-23 02:12
https://hypothesis.readthedocs.io/en/latest/packaging.html#release-tarballs

Not a bug, then.
