### ISSUE TITLE
min_satisfying_examples can be less than max_examples

### ISSUE THREAD

**Issue by bukzor** [HypothesisWorks/hypothesis-python#1215] opened 2018-04-05 23:36 UTC
This is silly, but my test didn't succeed because I had these settings, and it might be less obvious to other users, and I note that you do a fair amount of validation in _settings.py.

Please feel free to close if this falls below your priority threshold.

**Comment by Zac-HD** [comment] 2018-04-05 23:52
Duplicate of #197 - we definitely want to handle this, but don't currently have a good proposal.  Ideally our sensible heuristic would allow the `min_satisfying_examples` setting to be deprecated and handled entirely internally!

**Closed by Zac-HD** 2018-04-05 23:52 UTC

**Comment by Zac-HD** [comment] 2018-04-07 00:27
#535 for general settings simplification, #195 for this specific setting, or #1211 for the actual removal (should be merged in a few days).
