### ISSUE TITLE
fake_factory('uri') can raise HealthCheck errors when used by itself.

### ISSUE THREAD

**Issue by Daenyth** [HypothesisWorks/hypothesis-python#360] opened 2016-09-15 12:15 UTC
I have some code roughly like this:

``` python
from hypothesis import given, example
from hypothesis.extra.fakefactory import fake_factory
urls = fake_factory('uri')

@given(urls)
@example("http://http://example.com/foo")
@example("https://https://example.com/foo")
@example("http://https://example.com/foo")
@example("https://http://example.com/foo")
def test_normalize_url__is_idempotent(url):
    from myapp import normalize_url

    first = normalize_url(url)
    assert normalize_url(first) == first
```

This code raises `HealthCheck.too_slow`

**Comment by Zac-HD** [comment] 2017-05-24 07:16
I can't reproduce this on Hypothesis 3.8.6 or 3.11.0 (with `normalize_url = lambda url: url`), so I'll close the issue.

**Closed by Zac-HD** 2017-05-24 07:16 UTC

**Comment by Daenyth** [comment] 2017-05-24 18:38
This was filed on an older version so it's possible things have changed
