### ISSUE TITLE
strategies defined with map dont work correctly with @given

### ISSUE THREAD

**Issue by CodyKochmann** [HypothesisWorks/hypothesis-python#832] opened 2017-09-02 18:19 UTC
I have a client who needs some functions tested which all accept lists as their inputs. In order to get past the guards on some of the functions, specific members of the list have certain checks run against them which makes testing with a list filled with a single uniform type somewhat limited to only work with what the requirements of the most restricted element are.

To make it so I could have one element adhere to the restrictions and the rest can test wider, I made a function that takes multiple strategies and returns back a strategy that maps each input strategy to an element in a list. For example: a strategy that generates a list with a string and an int. 

When testing the joined list strategy with `.example()` to make sure I was generating the correct tests, things seemed to be working correctly. Then when it came time to give the strategy to `@given` the strategy seemed to only produce one result and just calls it a day there. 

I made an example below to cleanly sort of demonstrate the issue that is happening. I know this approach using map works well for other things like ipv6 generation like `ipv6 = st.integers(min_value=0, max_value=2**128-1).map(IPv6Address)` but for some reason this case behaves weird when it's run through `@given`. 
 
```python
Python 3.6.1 (default, Apr  4 2017, 09:40:51)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from hypothesis import given, strategies as st
   ...:
   ...: def multi_strategy_list_strategy(*strategies):
   ...:     """ makes a strategy that generates lists with multiple strategies making each element """
   ...:     return st.none().map(lambda n:[i.example() for i in strategies])
   ...:
   ...: # make a strategy that makes lists with a string as the first element and an int as the second
   ...: str_int_strat = multi_strategy_list_strategy(st.text(), st.integers())
   ...:

In [2]: # test the strategy to see that it works correctly
   ...: for i in range(3):
   ...:     print(str_int_strat.example())
   ...:
["\U000f2fdc\U000358f4\x16\U000c79cd\x08\x1f&\x17\x13\x0f\r\U000ac782'\x16𦲚\x14\U000d747d\x08\x17\U000db1a6)\U00039d52\U000b7298!𔑪", 46707789475428279362791651622419763081]
['\U000459dd0!\x07\U0004fd55\x1a\U000ae9ee*', -35226233061827404459578431761156017934]
['', -63242345993972436983377780194945636180]

In [3]: # now test it using given
   ...: runs = 0
   ...:
   ...: @given(str_int_strat)
   ...: def tester(args):
   ...:     global runs
   ...:     runs += 1
   ...:     print(runs, args)
   ...:

In [4]: tester()
1 ["\U000da16d'\U000ee906\U0008e1ab#$!\U000b1afa\x0f\x07", -85296636193678268231691518597782489127]

In [5]: tester()
2 ["\U000da16d'\U000ee906\U0008e1ab#$!\U000b1afa\x0f\x07", -85296636193678268231691518597782489127]

In [6]: tester()
3 ["\U000da16d'\U000ee906\U0008e1ab#$!\U000b1afa\x0f\x07", -85296636193678268231691518597782489127]

In [7]: tester()
4 ["\U000da16d'\U000ee906\U0008e1ab#$!\U000b1afa\x0f\x07", -85296636193678268231691518597782489127]

In [8]:
```

Thanks for the help in advance.

**Comment by alexwlchan** [comment] 2017-09-02 19:33
I can’t explain what’s going on, but I suspect the issue here is the use of `.example()` in `multi_strategy_list_strategy` – that’s really intended for interactive API work, not running proper tests. I’m pretty sure `@given` and `.example()` aren’t designed to work together.

In particular, I don’t think it has any of the nice shrinking behaviour of the regular strategies, because it finds an example out of sequence. It’s also biased towards simpler examples, which may not be desirable.

(@DRMacIver probably knows more detail, and may be able to explain what’s actually going on.)

The correct thing to do here would probably be to do something like `st.builds()`, although exactly what you’d write I’m not sure right now.

**Comment by alexwlchan** [comment] 2017-09-02 19:38
BTW, something I find odd and makes me think `.example()` is causing weird behaviour: if you try this with a regular strategy, each call to `tester()` gets you 200 examples, as you’d expect when you use `@given()` with the default settings.

For example:

```python
from hypothesis import given
from hypothesis.strategies import integers

runs = 0

@given(integers())
def tester(args):
    global runs
    runs += 1
    print(runs, args)
```

**Comment by alexwlchan** [comment] 2017-09-02 19:43
So I think this will do the trick for you:

```python
from hypothesis import given
from hypothesis.strategies import builds, integers, text

def multi_strategy_list_strategy(*strategies):
    return builds(lambda *x: list(x), *strategies)

str_int_strat = multi_strategy_list_strategy(text(), integers())

runs = 0

@given(str_int_strat)
def tester(args):
    global runs
    runs += 1
    print(runs, args)

tester()
```

In particular, because this one uses `builds()`, it draws multiple examples and I’m pretty sure it gets the usual behaviour around shrinking, examples database, etc.

@CodyKochmann Does what I’ve written make sense? Would the function above be suitable for your use?

@DRMacIver Have I written anything egregiously wrong in my last three comments? 😛

**Comment by CodyKochmann** [comment] 2017-09-02 20:02
I believe that will work. Is there a better way to pop single test inputs out of a strategy than calling `.example()`?  I'm not too familiar with the internals with hypothesis but when I want just a few from a strategy I'd think it would be something like `next(my_strategy)` if it worked like a native generator or `next(i for i in my_strategy)` if it had an iter but wasn't a generator yet.

I use `.example()` a lot for weird things but know that kinda degrades what I get back.

**Comment by DRMacIver** [comment] 2017-09-02 22:27
As @alexwlchan says, a good rule of thumb is that if you are using `example()` outside of the interactive terminal then you're probably doing something wrong. It exists for quick experiments while developing strategies, nothing else. Using `example()` inside a map will *definitely* not do the right thing.

(In general I second everythign @alexwlchan said as correct)

Details:

What's happening in the specific case you're getting is that from the `given` point of view you're not generating any data. The `example()` calls get their data from a fresh source, seeded from the global random number generator and unconnected to the given. So when given runs it sees you don't draw anything, concludes that your test only has one example, and stops. 

In terms of popping single inputs outside of a strategy, you probably want [composite](https://hypothesis.readthedocs.io/en/latest/data.html?highlight=composite#composite-strategies) for defining strategies (you could also use [data](https://hypothesis.readthedocs.io/en/latest/data.html?highlight=composite#drawing-interactively-in-tests) inside tests).

Also, `tuples` already works more or less like you want it to. `tuples(a, b, c)` will draw  tuple whose first argument comes from a, second from b, third from c, so you could just do `tuples(a, b, c).map(list)`.

**Comment by Zac-HD** [comment] 2017-09-03 07:06
Questions for maintainers:

- How can we improve the documentation so this is clear for new users?
- Can we detect and error on use of `s.example()` within `@given`?

**Comment by DRMacIver** [comment] 2017-09-03 10:31
> How can we improve the documentation so this is clear for new users?

I'm not even sure we have any explicit documentation for example in the docs. We should probably fix that. But honestly I don't think this problem can be solved with documentation.

> Can we detect and error on use of s.example() within @given?

I was thinking about this. I think the answer is yes, and I'll probably open a pull request doing just that in the next day or two. I think there's an open question on what is best to do and whether we can turn it straight into an error or need to start by emitting a warning. I strongly prefer doing the latter, but I think it requires a comb through the documentation to what we say about example.

**Comment by CodyKochmann** [comment] 2017-09-03 14:17
The biggest change I'd recommend is by advising the use of `build` instead of `.map()` for building custom strategies. Just going off of the docs, I knew `.map()` was a good method to get what I wanted into the strategy but I had no idea `build` was even a thing and from what I've seen in the last day or so, it works better and feels a lot less hacky than `.map()`

If I remember correctly, `build`'s documentation made it seem like it had a lot of potential but was too broad for me to understand how it worked so I just stuck with `.map()`

**Comment by DRMacIver** [comment] 2017-09-04 10:24
I'm going to close this issue as this is not a bug in Hypothesis and I think the original question has been answered at this point.

**Closed by DRMacIver** 2017-09-04 10:24 UTC
Labels: docs, question
