### ISSUE TITLE
Outline the process for issues labeled `for-a-modest-fee`

### ISSUE THREAD

**Issue by thijsvandien** [HypothesisWorks/hypothesis-python#723] opened 2017-07-09 23:32 UTC
Several issues have been assigned the label [`for-a-modest-fee`](https://github.com/HypothesisWorks/hypothesis-python/labels/for-a-modest-fee). Both my attempts to get in touch to potentially pay this modest fee, via email and by responding to the issue, have so far failed to produce any response. This made me wonder if I'm doing something wrong, or if my expectations in terms of response time are unreasonable.

Perhaps it would be useful to outline how to deal with issues labeled as such. Otherwise I don't really see how this model can be successful. At the very least, the following needs to be clear:
- How to get in touch
- What info to provide, if any
- Within how much time any response can be expected

Also useful, but context sensitive:
- The role of the funder – is it merely to pay, or is more involvement welcome or expected even?
- A rough indication of what 'modest' means
- Some general implementation timeframe (days, weeks, months...?)

**Comment by DRMacIver** [comment] 2017-07-10 13:46
Hi,

Sorry, I've been meaning to reply to you. Your email arrived when I was in the middle of travelling and I've failed to properly reply since getting back. My apologies, and you haven't done anything wrong.

I agree this needs better guidelines and outlining. We haven't actually been using the for-a-modest-fee label much recently - it's not entirely the right model I think - so a lot of the issues it's attached to are quite old.

Part of why I've been bad about getting back is because the particular one you've asked about is in that category, and I've been trying to figure out how to frame a response. The short answer is that I no longer think the issue is a good idea as written, and I'm probably going to end up closing it, but there might still be something we can do for your particular problem. I'll try to email you a longer answer later today.

**Closed** 2018-02-25 23:44 UTC
Labels: meta, question
