### ISSUE TITLE
`hypothesis.extra.django.models.models` is extremely slow to produce django `User` object examples

### ISSUE THREAD

**Issue by coriolinus** [HypothesisWorks/hypothesis-python#391] opened 2016-11-14 13:21 UTC
An example to show what I mean is simplest:

```python
$ ./manage.py shell
Python 3.5.2 (default, Jul 17 2016, 00:00:00)
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from time import time
>>> from contextlib import contextmanager
>>> @contextmanager
... def timed(fmt='{}'):
...     start = time()
...     yield
...     print(fmt.format(time() - start))
...
>>> from django.contrib.auth.models import User
>>> from hypothesis.extra.django.models import models
>>> with timed():
...     u = models(User).example()
...
8.897624731063843
```

That's the basic Django `User` model, not customized in any way, running against a sqlite instance on localhost. It gets worse when I try to define a customized strategy so I can generate only users of a particular type:

```python
>>> from hypothesis import assume
>>> from hypothesis.strategies import composite
>>> @composite
... def gen_user(draw, superuser=False, active=True):
...     user = draw(models(
...         User,  # generate a randomized User object...
...         is_superuser=just(superuser),  # which is only an admin if we've specified here...
...         is_staff=just(superuser),
...         is_active=just(active),  # which is active unless we've specified otherwise
...     ))
...     if user.last_login is not None:
...         assume(user.date_joined <= user.last_login)
...     return user
...
>>> with timed():
...     u2 = gen_user().example()
...
26.914336919784546
```

That's actually better than average: testing further, `gen_user().example()` as defined above returns in an average of 43 seconds, stdev of 16. 80% of the time it returns a value; the other 20% it complains that it can't find any suitable examples at all. For a single, simple, satisfiable constraint such as exists in that function, that's an unacceptably high failure rate. Moreover, it's hard to justify waiting 40 seconds per iteration generating a `User` object in a test which may run for hundreds of iterations.

Producing other model examples doesn't take nearly so long:

```python
>>> from core.models import UserProfile
>>> from hypothesis.strategies import just
>>> with timed():
...     up = models(UserProfile, user=just(u), photo=just('foo')).example()
...
0.21434950828552246
```

For my own test cases, I suppose I can just supply fixtures for the `User` model as required, but it doesn't feel elegant or in the spirit of what Hypothesis is supposed to offer.

**Comment by coriolinus** [comment] 2016-11-18 12:31
Further informal testing suggests that this is likely the result of the Hypothesis FakeFactory integration used to create the function; for whatever reason, calling `hypothesis.extra.fakefactory.fake_factory(type)` takes several seconds, and actually producing an example also takes non-trivial time. 

Haven't gone into as much detail timing that, as I've moved to using `User` model fixtures instead of generating them due to this speed issue. Still, I hope this helps figure out what's going on there.

**Comment by inglesp** [comment] 2017-01-18 20:22
I can reproduce slowish generation of `User` examples, but only for the first example.  Subsequent examples are generated much more quickly:

```
>>> with timed():
...     u = models(User).example()
... 
2.294529914855957
>>> with timed():
...     u = models(User).example()
... 
0.054763078689575195
```

This is because `User.last_login` is a `DateTimeField`, and hypothesis needs to [load a lot of timezone data from pytz](https://github.com/HypothesisWorks/hypothesis-python/blob/master/src/hypothesis/extra/datetime.py#L87-L90).  This takes a couple of seconds for me.

I thought I had seen more general slowness (in #429) but I now cannot reproduce that.

**Comment by Zac-HD** [comment] 2017-05-17 06:59
[Hypothesis 3.6.1](https://github.com/HypothesisWorks/hypothesis-python/blob/master/docs/changes.rst#361---2016-12-20), released 2016-12-20, included an alternative (and faster) emails strategy and fixes this issue (but apparently didn't close it).

A slow first draw caused by loading timezone data isn't ideal, but nor is it a bug.

**Closed by Zac-HD** 2017-05-17 06:59 UTC
